pool:
  name: Hosted Ubuntu 1604

trigger:
  - master
pr:
  - master

variables:
  dockerId: davidxchen
  imageName: blazing-dotnet-tweets-server

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 5.x'
  inputs:
    packageType: sdk
    version: 5.x
    installationPath: $(Agent.ToolsDirectory)/dotnet
    includePreviewVersions: true

- task: DotnetGlobalToolInstaller@0
  inputs:
    name: 'nbgv'
    checkLatest: true

- task: CmdLine@2
  inputs:
    script: 'nbgv cloud'

#- task: Cake@2
#  inputs:
#    script: 'build.cake'
#    target: 'Default'
#    verbosity: 'Verbose'

- powershell: |
   $version = nbgv get-version -f json | ConvertFrom-Json
   
   Write-Host $version.SemVer2
   Write-Host $version.NuGetPackageVersion
   
   [string] $SemVer2= $version.SemVer2
   Write-Host "Setting the version of the build to '$SemVer2'."
   Write-Host "##vso[task.setvariable variable=prereleaseVersionNumber]$SemVer2"

  displayName: 'PowerShell Script'

- task: Docker@2
  displayName: 'Build image'
  inputs:
    containerRegistry: '$(dockerId)'
    repository: '$(dockerId)/$(imageName)'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(prereleaseVersionNumber)
      latest
    arguments: '--build-arg APP_VER=$(prereleaseVersionNumber)'

- task: Docker@2
  displayName: 'push'
  inputs:
    containerRegistry: $(dockerId)
    repository: $(dockerId)/$(imageName)
    command: push
    tags: |
     $(prereleaseVersionNumber)
     latest
    